allowBuilds:
  dtrace-provider: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.12'
  - '@expo/router-server@57.0.5'
  - expo-constants@57.0.9
  - expo-modules-core@57.0.9
  - expo@57.0.10
  - expo-linking@57.0.5
