name: "Android"

on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 26.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - uses: expo/expo-github-action@v9
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Setup Global Gradle Memory and Repositories
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError" >> ~/.gradle/gradle.properties
          echo "settingsEvaluated { settings -> settings.pluginManagement.repositories { google(); mavenCentral(); gradlePluginPortal() } }" > ~/.gradle/init.gradle
      - name: Build package
        env:
          GRADLE_OPTS: "-Xmx4096m -XX:MaxMetaspaceSize=1024m"
        run: pnpm build:android:local
      - uses: WyriHaximus/github-action-get-previous-tag@v2
        id: currenttag
      - name: Rename AAB
        run: mv build-*.aab subadapp-${{ steps.currenttag.outputs.tag }}.aab
      - uses: softprops/action-gh-release@v3
        with:
          files: subadapp-${{ steps.currenttag.outputs.tag }}.aab
          tag_name: ${{ steps.currenttag.outputs.tag }}
